### ISSUE TITLE
Does the .exe contain a virus?

### ISSUE THREAD

**Issue by RonaldBolado** [CodeDead/AniView#4]
https://www.virustotal.com/gui/file/fb12d76af444181df43017b99af5a77e11b6a6ca9c4c96b81794c6b269ba8dc7/detection

**Comment by CodeDead** [comment]
Hello @RonaldBolado ,

This is the official image as seen from:
https://codedead.com/?page_id=1238

Unfortunately, some antivirus solutions automatically assign the label 'malware' to executable files they do not know and/or have seen before. This is known as a false positive. This is something that happens with pretty much every single release of any of our applications and should be cleared up in the future when those antivirus solutions update their malware databases.

Additionally, the portable version does not have any warnings at all:
https://www.virustotal.com/gui/file/e19b1292138f06b353efe86e827282c55c0370be881a9aaf249937b0ffc6b88b/detection

If you'd like to help us out, you can always contact the antimalware solutions that are marking our solutions as malware and report them as false positives.

If in doubt, you should always download any application from their official website. In this case that would be:
https://codedead.com/?page_id=1220 

In this case, you can even compile AniView yourself since it is fully open-source:
https://github.com/CodeDead/AniView

Kind regards
